<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?=$title?></title>
    <link rel="icon" type="image/x-icon" href="/images/favicon.ico">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="/public/css/style.css">
    <script type="module" src="/public/js/main.js" defer></script>

  </head>
  <body>

    <header>   
      <?php require $header.'.phtml' ?>
                <!-- Image bandeau-->
                <div class="bandeau-<?=$title?>">
        <h1 class="h1">Fishing logs </h1>
    </div>
    </header>




    <main>
      <?php require $template . '.phtml' ?>
    </main>

    <footer>
      <?php require $footer.'.phtml' ?>
    </footer>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
  </body>
</html>
