<main class="vh-90">
  <div class="container pt-5 mb-5">
    <h1>Formulaire d'inscription</h1>
    <form>
      <div class="form-group">
        <label for="email">Email :</label>
        <input type="email" class="form-control" id="email" placeholder="Entrez votre adresse email" required>
      </div>
      <div class="form-group">
        <label for="motDePasse">Mot de passe :</label>
        <input type="password" class="form-control" id="motDePasse" placeholder="Entrez votre mot de passe" required>
      </div>
      <button type="submit" class="btn btn-primary">Se connecter</button>

    </form>
</div>
<a href="#" class="float-right">Mot de pass oublié ?</a>
</main>