<nav class="navbar navbar-expand-lg navbar-light">

          <img src="/public/img/logo.png" alt="logo" srcset="" class="logo">

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="nav-container" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Accueil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/history">À propos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact">Contact</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/login">Se connecter</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/subscribe">S'inscrire</a>
                </li>
            </ul>


        </div>
    </nav>

