<?php
return [
        '/'=>[
            'Controllers\HomeController',
            'index'
        ],
        '/index.php'=>[
            'Controllers\HomeController',
            'index'
        ],
        '/login'=>[
            'Controllers\LoginController',
            'login'
        ],
        '/subscribe'=>[
            'Controllers\SubscribeController',
            'subscribe'
        ]
    ];