<?php
return [
        '/'=>[
            'MVC\Controllers\HomeController',
            'index'
        ],
        '/index.php'=>[
            'MVC\Controllers\HomeController',
            'index'
        ],
        '/history'=>[
            'MVC\Controllers\HistoryController',
            'history'
        ],
        '/contact'=>[
            'MVC\Controllers\ContactController',
            'contact'
        ],
        '/login'=>[
            'MVC\Controllers\LoginController',
            'login'
        ],
        '/subscribe'=>[
            'MVC\Controllers\SubscribeController',
            'subscribeDisplay'
        ],
        '/subscribeForm'=>[
            'MVC\Controllers\SubscribeFormController',
            'subscribe'
        ],
    ];